# Generated by Django 4.1.7 on 2023-04-06 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_id", models.IntegerField(default=0)),
                (
                    "class_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("student1_presest", models.CharField(max_length=1)),
                ("student2_presest", models.CharField(max_length=1)),
                ("student3_presest", models.CharField(max_length=1)),
                ("student4_presest", models.CharField(max_length=1)),
                ("student5_presest", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField(default=0)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=40)),
                ("student_number", models.CharField(max_length=5)),
                ("course", models.CharField(max_length=10)),
            ],
        ),
    ]
