# Generated by Django 4.1.7 on 2023-04-26 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="attendance",
            fields=[
                ("attendance_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("john_present", models.CharField(max_length=255)),
                ("michael_present", models.CharField(max_length=255)),
                ("beth_present", models.CharField(max_length=255)),
                ("nick_present", models.CharField(max_length=255)),
                ("mark_present", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="students",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=40)),
                ("student_number", models.CharField(max_length=5)),
                ("course", models.CharField(max_length=10)),
            ],
        ),
    ]
