# Generated by Django 4.1.7 on 2023-04-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_django", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="id",
        ),
        migrations.RemoveField(
            model_name="students",
            name="id",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="students",
            name="student_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
